# Generated by Django 5.2.1 on 2025-06-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_product_category_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_code',
            new_name='cart',
        ),
    ]
