# Generated by Django 5.2.1 on 2025-06-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_rename_cart_code_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_ate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
